cache:
  key: ${CI_PROJECT_NAME}
  paths: # cache everything so that unnecessary recompilation is avoided
    - lib
    - cmake
    - example
    - test
    - CMakeLists.txt
    - Doxyfile.in
    - build
job:
  image: pjknowles/opensuse
  script:
    - procs=$(lscpu -p | egrep -v '^#' | wc -l || echo 1); echo $procs processors available
    - TOP=$PWD
    - ls -lR dependencies
    - git checkout $CI_COMMIT_SHA # because of cache
    - ls -lR dependencies
    - git reset --hard
    - ls -lR dependencies
    - git clean -f src lib test dependencies
    - ls -lR dependencies
    - cd $TOP; BUILD=build; mkdir -p $BUILD && cd $BUILD && pwd && cmake -DMPIOPTIONS="--allow-run-as-root" $TOP ; cmake --build . -- -j ${procs} ; cd test;  ctest -V -j ${procs}

#image: alpine:latest
image: pjknowles/opensuse

pages:
  stage: deploy
  script:
    - rsync -a --delete build/html/ public
  artifacts:
    paths:
      - public
#  only:
#    - master

