cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - public
image: pjknowles/opensuse

build:
  script:
    - procs=$(lscpu -p | egrep -v '^#' | wc -l || echo 1); echo $procs processors available
    - TOP=$PWD
    - git checkout $CI_COMMIT_SHA # because of cache
    - git reset --hard
    - git clean -f src lib test dependencies
    - cd $TOP; BUILD=build; mkdir -p $BUILD && cd $BUILD && pwd && cmake -DMPIOPTIONS="--allow-run-as-root" $TOP ; cmake --build . -- -j ${procs} ; cd test;  ctest -V -j ${procs}
    - rsync -a --delete $TOP/build/html/ $TOP/public

pages:
  stage: deploy
  script:
    - echo nothing
  artifacts:
    paths:
      - public
#  only:
#    - master

